sudo: false
cache: pip
language: python

env:
  global:
    - secure: YGpGnxf9XMnwFiOyXKvl8XiDodhPIN7+PzOytJ0bodNvhriaua8Y54NT04WXLzpcg59t0Bp0Yd6gUERuyZ4cslBBpHtfl74iUOJPOEk/V7H0562C7TAxXxI9+XltYBhnv55Bxq/4B1Rj0YQxJ0Dl3CMfJGovAPs6zLUA7p2fz+kkhIDcc4DC2l7DE3rYhUsRCYakjaCpGSfPT1LSOBheGPWN3taPnANr0M9pTDI+Ej+kpfip7Sxna+phKZjvy9gsdhr4Wbca52826wj29E3B2Z4qw1wBVTqCzT6oPTvLt2++etbAfDkGohXy0zBOHDy2nN9oILIci5GMYd6qivQTu2gQBM7n0woMjk3NNe6buu23t7DpI9EuVpEl/3ocPdqDudaR9kW5UyWYJd0lvEJeTUolKjDGnUiDEh/tDAvgXtWiqi8DTZJTnwDwFpGB8eKNPqJhbUL9lj7HtfyElwTzJyHViwJRvAtvbMCtLroEVZau41+cTS2aIVkJLUP7ECpIKXWNGzmhfTBWsuF2aKnEH3onG84/QbuS8ADFD5XAKUP9fyq7qK7sf2loDrhSrGG2f8laIrL53ZiUgQItmcHBqW64eXILJwHN4loucc+X/gS27mNPZQZGxdF1UmWTUUnzVCTmrrL8hQqVi4Kue7j2TLtX6GCaocZ+VTS2qVWO3RI=
    - secure: DAQBtOrsIbNav3Ac8FLKjOQNfnlPMX+cXRk4SfjvfxJciA8W16Aa2ZyYhC0AZiEBQbMwslYS2WyYNU3+NsQfoCJ+KoWYbnfT/qfvn+K+f0uKZTazZaOHSJA4tOs6kA88L1X5yHOwMalQqyRUEkQ1lHxcGxmjMFDi+FdsCLDVQIuLaAn+Apk3TNGXKzV7IaYNkHO5kQmTrl4/v8epJcD35lo5Yw8SkUGgo0rPosecXvZU3ZoR9CpFWfBid+NECYrv8Cp7syTT9srp0y95sE38wCwr9nttNmcCKe3fLGygh0RBLyrkNl6Ajpk7qJVaa2/McIO3+4qekXlCt7dX4UpEWUH3wDjHGb//JdsaLgIMTLWP393hm4g1SJQgnPCjVi/4hxfcGfF08dnQw4JYAHC4z1qjae5A6zoI30JHOqwH4Yu3Rj9GhFhsWNA7I2kNXg/el+df23jA7mxWfXwuY5YLck156NXij8vhLYGxltgDEtmp6U1bnppQpaJKxn/9dcXZCsbJb+x8FZ0OF3lkq82vnnXAZuQ41gTosuSg1w9DQKF6OImAG0KVXDwd5qTwp8thXdrVSRXKcUltvIT9+W7kyMEKHnusLJruOvtAuCNLArSE5keJdqtb+POLfOp9ZrUObs0j/77zfZH85VmjWspWkn9rZ1v10gYHZv6Lu8NHbCM=
    - secure: bJrbXXuC9O/2YazHi9D95rWiPPDyDlVUE1i9WSos3lMAbqapn2vKL2gRosrM1NcIVIhnAzwi7O8ngQRiKID7nWF1xYGhapZcIya3q6z40m0HNQus+XngzSCTNaWVCMqEASDGluHOLlc/Vnbip/3tcgUSlGHk6P1p/zzoUbMKOa0igcnCG0kxR6BkcrPL1qIWdCMTDkGlmT7IFHF4ilFkhGJWssjR4mFFZX2awJJtQ2BmudsUKeytNjUI3/yQyV3eoQo2EXQDcU34ObkZFZkymdPBqfy3sSw3To2JLc4aiq/iZzIfItUaUcWS7T9HbhUD1aDG4pWWhqCBdPDbwcc0XklgX5eL9ZXI9s++gKMO7V5nu4GSE39ShYruyq8mPiRVGO4oCUFPP1N8ZMFaXLEMg5Wa4s+VxuHSMB70l5VeL7UvorJ+Ij4djBtn2RF6IYymvpDH3q5n4W2BciVg7LRZ1GX8TtSZNae4O09qYQhMGQNIKCNykbvx3DJamcI1q54kJTCjub9RVcvzUxap0PgTxjHrGB7M90wg9bHmvTaJvl7fkFC8yrtOQ/vjwttiq5X7SCrEHaBSV9TEbLOB3jB2bIfLQ92T2USjbExetOartz/P+X1dreECHXhk9g55qAvob4k3uCE3K+WAEdbVw39mqhfUPz0iuKqTsrJJ5fNyX2Y=
    - secure: d6W0/c04ea+0Lb5FXzzVcV4yVSqEMwrB1DOEpRapTP50a6JumziLKhIyDyzsJMgqVmkGQsAgfDNtGOZ1k/UiA3rjSXlQ5YgIwQpr0xgntKDq1/Ha02xxBpXfaS+ts3cnygldOGKF7jtPOJ+sb3hSdVmX1+q25OoyW8VtUT3GVtK0vERKxePdNzwOmrUXihYsvMMDrebmvcQvXHyk0UhtKnPlYVfyzcqoRBhlKUkUfU1LhLDQvewWcwwg7fC+7eK3Njx7EyIZ2sxU2IzDsE933YksVmJKowZOZtJsfOh6e1dspmP5Id9bGl4wTH68IzoFXzEi+/RAo68wXRjL39G6/WaRqph7YQHtLfqak1zLM7Gh0jxYSseWyYAW29RbLV71H4isXG8X6lOQE8hq9VxLaXoWx9HHaCJWuQUZVGlcnlvOcOxlr+FKmG29Z3zm9RtsZuGuZXm3+Ndf32ZBebGr5RQg5R4kkb2R/BIcm/+FBYRdCO6zjx894VXDUdUDuuwSPj0V9EvhUEEcKxwjxezIvcyE6/GC+FirhESSU/b5ufWEIW2O3TAMJxthUN5QX9JUV4+4rNhW70Y968u/BbZBCIC6fYl4UXFNl3f+I09hs6EhMVWK88ytszn+L0dACnIpedKVeJQ46GNkiX5pwve/oLtaww1cHGWP+WJNNGQmACc=

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: required

script:
  - cd $TRAVIS_BUILD_DIR
  - |
    if [[ "$TRAVIS_TAG" == "" ]]; then
        sed -i "/__version__ = / s/\"$/.20$TRAVIS_BUILD_NUMBER\"/" odbcli/__init__.py
    fi
  - pip install --upgrade --upgrade-strategy eager . twine pytest
  - pytest . 
  - python setup.py sdist

deploy:
  - provider: script
    skip_cleanup: true
    script: $TRAVIS_BUILD_DIR/ci/travis/deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: $TRAVIS_BUILD_DIR/ci/travis/deploy.sh
    on:
      tags: true
